### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by ClemGlacee** [Jaid/entity.works#28]
https://entity.works/build
We can't build any loadouts :(

PS: Your loadouts are kinda bad...

**Comment by Jaid** [comment]
> We can't build any loadouts :(

I pushed a fix to the login management in the backend.
Should be fixed now. Please try again!

Here is your input data, so you don't have to type all that again:

```
Locker Combo

If you want to play around lockers and have fun with those, then this build is the one you need!
Inner Strength gives you the ability to heal yourself
Decisive Strike (DS) can make you escape if the killer grabs you in a locker
Quick & Quiet will make you get in faster and without making any noise
and Head On will give you the ability to stun the killer if he comes to close to your locker
```

> Your loadouts are kinda bad...

Most likely. I wouldn't say I am a good player myself. 😅

**Comment by ClemGlacee** [comment]
Your website is awesome though!
It would be nice to have a sort of comment section for the builds with ratings like thumbs up/down
and I also thought of something else for the website, I'm not sure if that's really good but something like loadout categories for differents ranks tier (a rank 1 wont usually use the same perks as a rank 20)

Thank you very much :)
By the way, how do you put the perks in the description like you did with your other guides

**Comment by ClemGlacee** [comment]
Also, the ability to edit your guides would be very neat

**Comment by Jaid** [comment]
> Also, the ability to edit your guides would be very neat

Editing should be working now.

> how do you put the perks in the description like you did with your other guides

Write the ID of an object with braces like `{noMither}`. A list of all objects is here: https://entity.works/objects

Ratings / comments / categories may come later.
